INSERT INTO CROP (ID, NAME) VALUES (1, '딸기');
INSERT INTO CROP (ID, NAME) VALUES (2, '벼');
INSERT INTO CROP (ID, NAME) VALUES (3, '감자');
INSERT INTO CROP (ID, NAME) VALUES (4, '상추');
INSERT INTO CROP (ID, NAME) VALUES (5, '사과');
INSERT INTO CROP (ID, NAME) VALUES (6, '고추');